version: '3'
services: 
  web:
    build:
      context: .
    env_file: ./.env
    command: npm run dev
    volumes: 
      - ./:/app/
      - node_modules:/app/node_modules
    ports:
      - '${APP_PORT:-300}:${DOCKER_PORT:-3000}'
    depends_on: 
      - db
      - redis
    networks:
      - nodeapp
  db:
    image: mysql:latest
    env_file: ./.env
    environment: 
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_USERNAME}'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - nodeapp
  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - nodeapp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
networks:
  nodeapp:
    driver: bridge
volumes:
  node_modules:
    driver: local
  mysql: 
    driver: local
  redis:
    driver: local